const CART = {
    ADD_TO_CART: "ADD_TO_CART",
    INCREASE_QTY: "INCREASE_QTY",
    DECREASE_QTY: "DECREASE_QTY",
    REMOVE_ITEM: "REMOVE_ITEM",
    EMPTY_CART: "EMPTY_CART",
    FETCH_CARTLIST: "FETCH_CARTLIST"
}

const WISH = {
    ADD_TO_WISH: "ADD_TO_WISH",
    REMOVE_WISH_ITEM: "REMOVE_WISH_ITEM",
    EMPTY_WISH: "EMPTY_WISH",
    FETCH_WISHLIST:"FETCH_WISHLIST"
}

const CLEAR_DATA = "CLEAR_DATA";

const STORE = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_CATEGORY:'FETCH_CATEGORY',
    FILTER_GENRE:'FILTER_GENRE',
    CLEAR_GENRE:'CLEAR_GENRE',
    SORT_PRODUCTS: 'SORT_PRODUCTS',
    TOGGLE_INVENTORY: 'TOGGLE_INVENTORY',
    TOGGLE_DELIVERY: 'TOGGLE_DELIVERY',
    SEARCH_STORE:'SEARCH_STORE'
}


export { CART, WISH, STORE, CLEAR_DATA}